const express = require('express');
const cors = require('cors');
const path = require('path');
const app = express();
app.use(cors());
app.use(express.json());
app.use(express.static('public'));
app.get('*', (req, res) => res.sendFile(path.join(__dirname, 'public', 'index.html')));
app.use('/api/chat', require('./api/chat.cjs'));
app.listen(3000, () => console.log('Server running on http://localhost:3000'));
